### ISSUE TITLE
Unable to Tap Due to ":latest" Versions

### ISSUE THREAD

**Issue by mca-gif** [athrunsun/homebrew-linuxbinary#5]
I just installed Homebrew 1.0.6 on top of a clean OS and am unable to tap the repo due to the changes made today.

> $ brew --version
> Homebrew 1.0.6
> Homebrew/homebrew-core (git revision 2d6a; last commit 2016-10-12)
> 
> $ brew tap athrunsun/linuxbinary
> ==> Tapping athrunsun/linuxbinary
> Cloning into '/home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary'...
> remote: Counting objects: 32, done.
> remote: Compressing objects: 100% (31/31), done.
> remote: Total 32 (delta 4), reused 9 (delta 1), pack-reused 0
> Unpacking objects: 100% (32/32), done.
> Checking connectivity... done.
> Error: Invalid formula: /home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary/Formula/dbeaver-ce.rb
> version ':latest' should be a string
> Error: Invalid formula: /home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary/Formula/teamviewer.rb
> version ':latest' should be a string
> Error: Invalid formula: /home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary/Formula/dbeaver-ee.rb
> version ':latest' should be a string
> Error: Invalid formula: /home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary/Formula/sqltabs.rb
> version ':latest' should be a string
> Error: Invalid formula: /home/matthew/.linuxbrew/Library/Taps/athrunsun/homebrew-linuxbinary/Formula/ffmpeg-binary.rb
> version ':latest' should be a string
> Error: Cannot tap athrunsun/linuxbinary: invalid syntax in tap!

**Comment by athrunsun** [comment]
@mattandersen Thanks for reporting this issue!

I was making this change based on homebrew cask fashion, which would certainly not work in linuxbrew.

Have you found anything related in linuxbrew's documentation? I think we really need to set `version` for these formulas to sth like "latest" or "stable" and skip sha256 check because their urls don't include anything related to version numbers, which will cause sha256 check failure once they're updated.

Also I'll try to add a CI build in travis ci to perform an audit for all formulas after a push or a PR created.

**Comment by athrunsun** [comment]
Rolled back to last workable version for now.
